### ISSUE TITLE
Configuration items

### ISSUE THREAD

**Issue by rendayigit** [rendayigit/SpaceLoader#96]
There shall be a configuration yaml file to store:

- ip port history of gui login page
- ip port history of gui egse page
- filetransfer path histories of gui filetransfer page
- ip port history of gui listenTo page

**Comment by rendayigit** [comment]
``` yaml
Config:
  Ips:
    targetPc:
      ip: 192.168.1.2
      port: '1234'
    egse: 
      ip: 192.168.1.250
      port: 5004
    listenTo:
      ip: 192.168.1.2
      port: 1239
  FileTransfer:
    remotePath: "D:/"
```
